language: node_js
node_js:
  - 'stable'
cache: npm
script:
  - echo "Building"
branches:
  only:
    - master
install:
  - npm install -g firebase-tools
build:
  - yarn build
after_success:
  - firebase deploy --project awk-dating --token $FIREBASE_TOKEN
