language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - node_modules
script:
  - echo "Building"
branches:
  only:
    - master
install:
  - npm install -g firebase-tools
  - npm run build
after_success:
  - firebase deploy --project awk-dating --token $FIREBASE_TOKEN
