language: node_js
node_js:
  - '8'
cache:
  directories:
    - node_modules
before_install:
  - npm install -g firebase-tools
after_success:
  - npm run build
  - firebase deploy --project awk-dating --token $FIREBASE_TOKEN
branches:
  only:
    - master
